DROP TABLE IF EXISTS CLIENTS CASCADE;
DROP TABLE IF EXISTS CREDITS CASCADE;
DROP TABLE IF EXISTS BANKS CASCADE;
DROP TABLE IF EXISTS LOANS CASCADE;
DROP TABLE IF EXISTS BANKS_CLIENTS CASCADE;
DROP TABLE IF EXISTS BANKS_CREDITS CASCADE;


CREATE TABLE IF NOT EXISTS clients
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fio      VARCHAR(255)                            NOT NULL,
    phone    VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    passport VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_client PRIMARY KEY (id),
    CONSTRAINT uq_client_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS credits
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    limit   BIGINT                                  NOT NULL,
    percent BIGINT                                  NOT NULL,
    CONSTRAINT pk_credit PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS banks
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_bank PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS loans
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id     BIGINT                                  NOT NULL,
    credit_id     BIGINT                                  NOT NULL,
    sum_of_credit BIGINT                                  NOT NULL,
    CONSTRAINT pk_loan PRIMARY KEY (id),
    CONSTRAINT fk_loans_to_clients FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE,
    CONSTRAINT fk_loans_to_credits FOREIGN KEY (credit_id) REFERENCES credits (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS banks_clients
(
    bank_id   BIGINT,
    client_id BIGINT,
    CONSTRAINT pk_bcl PRIMARY KEY (bank_id, client_id),
    CONSTRAINT fk_bcl_to_banks FOREIGN KEY (bank_id) REFERENCES banks (id) ON DELETE CASCADE,
    CONSTRAINT fk_bcl_to_clients FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS banks_credits
(
    bank_id   BIGINT,
    credit_id BIGINT,
    CONSTRAINT pk_bcr PRIMARY KEY (bank_id, credit_id),
    CONSTRAINT fk_bcr_to_banks FOREIGN KEY (bank_id) REFERENCES banks (id) ON DELETE CASCADE,
    CONSTRAINT fk_bcr_to_credits FOREIGN KEY (credit_id) REFERENCES credits (id) ON DELETE CASCADE
);

INSERT INTO CLIENTS (fio, phone, email, passport) VALUES ('Ivanov Ivan Ivanovich', '111-111', 'ivan@mail.ru', '333-333');
INSERT INTO CLIENTS (fio, phone, email, passport) VALUES ('Petrov Petr Petrovich', '222-222', 'petr@mail.ru', '444-444');
INSERT INTO CREDITS (limit, percent) VALUES (1000000, 10);
INSERT INTO CREDITS (limit, percent) VALUES (2000000, 8);
INSERT INTO BANKS (id) VALUES (0);
INSERT INTO BANKS (id) VALUES (1);
INSERT INTO BANKS_CLIENTS (bank_id, client_id) VALUES (0, 0);
INSERT INTO BANKS_CLIENTS (bank_id, client_id) VALUES (1, 1);
INSERT INTO BANKS_CREDITS (bank_id, credit_id) VALUES (0, 0);
INSERT INTO BANKS_CREDITS (bank_id, credit_id) VALUES (1, 1);
INSERT INTO LOANS (client_id, credit_id, sum_of_credit) VALUES (0, 0, 500000);